<?php

/**
 * Implements hook_layout_alter().
 *
 * Unset the layouts provided by Panels that are incompatible with our theme. We
 * need to let `onecol` stick around because Panelizer seems to default to that
 * when first panelizing a layout - which causes an exception if it doesn't
 * exist.
 */
function speedrun_layout_layout_alter(array &$definitions) {
  $remove = ['Columns: 2', 'Columns: 3'];

  foreach ($definitions as $key => $info) {
    $category = $info['category'];
    if ($category instanceof \Drupal\Core\StringTranslation\TranslatableMarkup) {
      $category = $category->getUntranslatedString();
    }

    if (in_array($category, $remove)) {
      unset($definitions[$key]);
    }
  }
}
